### ISSUE TITLE
Is it possible to run a command (wakatime-cli) to statistic the time of browsing pdf?

### ISSUE THREAD

**Issue by Freed-Wu** [pwmt/zathura#571]
Is it possible to run a command ([wakatime-cli](https://github.com/wakatime/wakatime-cli)) to statistic the time of browsing pdf? By a new plugin?

I take a look at the plugin of zathura, it looks like they will register some functions for some specific mime types.

**Comment by alerque** [comment]
Why not either query your window manager or write a wrapper script that logs your time outside of running some job (like a viewer)?

**Comment by Freed-Wu** [comment]
wakatime plugins only statistic real working time. For example, wakatime editor plugin will not statistic time if users stop moving cursor for > 4 minutes. So IMO, wakatime plugin for pdf browser will also detect page up/down action in order to statistic real working time.

**Comment by alerque** [comment]
I suppose everybody's usage is going to vary, but with my PDF usage that metric would show next to zero activity when in reality I was constantly referencing a document. The only close approximation for me would be input focus as measured by the Window Manager (not `zathura` input activity), but even that would fall pretty flat because I frequently have an N-up (2, 4, 6, 8, even more) layout spread over one monitory and am coding on another and even if my eyes keep track of stuff in the PDF my input focus may not even end up on in (much less actually sending it input) for long stretches.

Wouldn't a more robust solution for the majority of users be to monitor input activity globally (i.e. from the window manager), then track what program is active during that time, then and only then resort to plugins inside apps for deeper metrics like actual files open or whatever else?

**Comment by sebastinas** [comment]
As others have suggested, there are other layers that you could hook into to handle that in a more general way. In any case, it'd be vocal against any kind of monitoring in any other software, so this is something that is definitely not going to be supported by zathura.
