### ISSUE TITLE
Position lost when reloading file

### ISSUE THREAD

**Issue by ghbrown** [pwmt/zathura#603]
Like many other users, I use Zathura as my PDF viewer for LaTeX writing, so Zathura has the PDF open when I rebuild the PDF.

Since my latest update via `pacman` Zathura no longer holds the proper position in the file when the PDF is rebuilt.

However, if I open a file, navigate to position X, close Zathura, then reopen the file it opens to X no problem. Seems there's something special about the rebuild of an open file that's causing issues for position.

System info:
```
EndeavourOS
zathura 0.5.6
girara 0.4.4 (runtime: 0.4.4)
(plugin) pdf-poppler (0.3.2) (/usr/lib/zathura/libpdf-poppler.so)
```

**Comment by sebastinas** [comment]
Please provide a log (with `-l debug`) with a4ef953 from the develop branch or newer.

**Comment by ghbrown** [comment]
Working on this now. How do I find the correct path for a plugin?
I'm currently running the newly compiled version like
```bash
<absolute path>/build/zathura -p /usr/lib/zathura main.pdf
```
I'm using this plugin path since it's what my installed zathura returns from `zathura --version`, but it doesn't seem to be working:
```
warning: Found no plugins. Please install at least one plugin.
info: Opening plain database via sqlite backend.
warning: sqlite database already exists. Set your database backend to sqlite. See zathura
rc(5) for details.
error: Could not determine file type.
```

**Comment by sebastinas** [comment]
Right, the path is correct, but the plugin ABI changed. You'll need to rebuild the plugins against the zathura version from `develop` (best to also use the develop version of the plugins).

**Comment by ghbrown** [comment]
When you say "against the zathura version" from the develop branch, what do you mean?
I've build `zathura-pdf-poppler` according to its build instructions, and I'm now passing this path (which contains `libpdf-poppler.so`), but I'm getting the same error.

I think perhaps the answer to both is that I haven't `ninja install`ed zathura (just to keep my machine as clean as possible). Is this what is needed before building `zathura-pdf-poppler`?

**Comment by ghbrown** [comment]
Indeed that was what I needed to do. Attached is the log.

I opened the PDF, scrolled down a bit, rebuilt via `latexmk` (which generates a new pdf). The bug was present, so it went back to the beginning.
[debug.log](https://github.com/user-attachments/files/15946353/debug.log)

**Comment by sebastinas** [comment]
Thanks. Could you also check the entry of the `fileinfo` table in `~/.local/share/zathura/bookmarks.sqlite` for that file (with `sqlitebrowser`, for example)? What does it contain for `page`, `position_x` and `position_y`?

**Comment by ghbrown** [comment]
Sure, here that is.
```
page: 0
offset: 0
position_x: 0.5
position_y: 0.0125277...
```

**Comment by ghbrown** [comment]
I believe what's happening is that if the file Zathura is displaying ever stops existing, all the metadata in the database is thrown out (or otherwise irretrievable) later if the file is to pop back into existence.

Something like the following reproduces the issue (no LaTeX needed):
```bash
zathura main.pdf &
<scroll down a bit>
mv main.pdf temp.pdf   # zathura display goes dark as expected
mv temp.pdf main.pdf  # at top of file, old position not saved
```

**Comment by ja-he** [comment]
I believe I am hitting this bug[^1] frequently in a new workflow where the PDF in question gets recompiled on every keystroke (with a Typst language server). Eventually (and usually after only a few dozen keystrokes) the scroll of my PDF preview in Zathura resets to the front of the document and the logs state `error: could not open document`.

Just wanted to add this to the issue since Zathura is by far the best PDF viewer to use for this preview-while-working purpose, yet this behaviour of forgetting about a file if it ever goes away for a moment completely ruins that workflow.

[^1]: honestly doesn't even seem like a terrible behaviour for some use cases, just inconvenient for some others.

**Comment by orlitzky** [comment]
This won't be a great solution for most people, but just in case it helps: I worked around this my making my preview/rebuild smarter.

LaTeX is an unusual compiler in that the names of the output files are inferred from the input files. This means that, if you're rebuilding in the current directory, the obvious and easy thing to do is to rebuild over the current PDF. If you want to compare the old version and the new one (to know when you're done resolving references and whatnot), then you'll probably choose to rename the just-built PDF to e.g. `<something>.old.pdf`, and then run the build job again. But this is essentially what's happening in https://github.com/pwmt/zathura/issues/603#issuecomment-2198249594, and it triggers the loss of position in Zathura. Even if nothing changes between runs of pdflatex, the open document has been changed to a new file with the same contents.

Avoiding that meant figuring out a way to build the document and not overwrite the existing one. Basically, I wanted to create `<something>.new.pdf` and do the comparison before clobbering the old version rather than moving the current version to `<something>.old.pdf` and re-creating `<something>.pdf`. This does not seem easy with pdflatex. But what did eventually work is to run the build in an entirely different directory by passing `--output-directory build` to pdflatex. The document still winds up named `something.pdf`, but it's `build/something.pdf`, and doesn't immediately overwrite the document that Zathura has open. This lets you check the exit code (to make sure that the build worked) and compare the two versions (to avoid pointless updates) before doing anything. And when you do modify the open document, it's without changing the name -- it's just a `mv build/something.pdf ./something.pdf`. Zathura seems unbothered by this.

**Comment by laomuon** [comment]
> This is fixed by #642, right?

Yes it is

**Comment by ghbrown** [comment]
This can be closed then, right?

**Comment by ja-he** [comment]
In my experience _this_ is very well resolved, yes. (And thanks to @laomuon for the fix!)

Largely unrelated: I am now experiencing a separate issue with frequently rebuilt PDFs where Zathura segfaults when image data ends up temporarily corrupted; I plan on filing an issue with some details as soon as I find the time.
