### ISSUE TITLE
Unable to map a binding more than one key with Special keys

### ISSUE THREAD

**Issue by YasserKa** [pwmt/zathura#665]
I am unable to map a binding that include a Special key, such as `<Space>`, with another key.
e.g. 
```
# Doesn't work
unmap <Space>
map <Space>w follow
# Works
map ee follow
```

**Comment by laomuon** [comment]
@YasserKa Currently this is not supported. The key parsing algorithm needs to be reworked in order to handle this. Right now, if you do 
```
map <Space>w follow
```
Zathura will register as the string sequence "<Space>w" and not as the `Space` key and the `w` key. You can try to type the sequence in and see that the follow function does indeed get called :)

**Comment by YasserKa** [comment]
Thank you for the clarification. I will close the issue, since the problem isn't with Zathura.
